spring.datasource.url=jdbc:mysql://localhost:3306/forumhub
spring.datasource.username=root
spring.datasource.password=Rarplia91

# Configurações para vermos o SQL gerado no console (ajuda muito a achar erros)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Desabilita a criação automática de tabelas pelo Hibernate, pois usaremos o Flyway
spring.jpa.hibernate.ddl-auto=validate